implement some dialogs
ubports/morph-browser pull request #16
Opened 2018-07-27 22:13 UTC by balcy

java script dialogs (alert, unload, confirm...), file upload, geolocation, color (new), ...
note: media access (camera, mic) did not yet work (regardless of the dialog implementation)
not yet done: downloads handling / fullscreen request

2018-08-09 17:48 UTC, balcy commented
note: the text select/copy/paste function not as good as in the old browser (dialogs should appear next to the text fields), so just interim version here until proper text selection works

2018-08-24 17:11 UTC, Flohack74 requested changes

2018-08-24 17:11 UTC, Flohack74 commented on src/app/WebViewImpl.qml
> +                    webview.runJavaScript("var elemContextMenu = document.elementFromPoint(%1, %2);
Missing a " at the end?

2018-08-24 17:21 UTC, balcy commented
should be fine, it is a two line java script command (the " is before the .arg() in the next line)
[edit] no idea why github makes those lines red, Qt Creator did not complain about them, and it worked ... to make it more readable, I've put the command to the variable "javaScriptCommand" now.

2018-08-25 07:51 UTC, balcy commented
just do not trust github, but me (and QtCreator) here : )
even Qt tutorials get those red lines:
https://github.com/qt-labs/qml-presentation-system/blob/master/examples/tutorial/SlideDeck.qml

2018-08-25 14:00 UTC, Flohack74 approved these changes

2018-08-25 18:48 UTC, Flohack74 commented
Hmm you want to keep the PR open? You are still adding stuff...

2018-08-25 21:11 UTC, balcy commented
For new stuff I can make a new PR
e.g. downloads are still missing.
But I will be on vacation without laptop soon, so it might be a good moment making a stop for now. : )
it surely will need some polishing later on.

2018-08-26 07:53 UTC, Flohack74 commented
Yes so stop here and make a new one if needed. Still waiting on @mariogrip review here ;)

2018-09-13 23:06 UTC, merged