Tab bar removal from subpages
ubports/morph-browser pull request #345
Opened 2020-07-21 00:14 UTC by mateosalta

Remove bottom new tab bar from pages not related to tab usage

## History page:
- remove bottom tab bar
- add 'edit' button for better discovery of edit options, and match downloads page
- on domain selection make 'less' button into a close 'x'
- domain selection header height match

## Bookmarks
- remove bottom tab bar

2020-08-10 00:00 UTC, cibersheep commented
Coooool.Coolcoolcool

2020-08-14 03:17 UTC, mateosalta commented
oh! I missed that one :)

2020-08-14 17:02 UTC, mateosalta commented
And done :)

2020-11-26 17:44 UTC, mateosalta commented
Hi @UniversalSuperBox , can this one be considered for ota-15. It goes together well with @cibersheep's color changes, as he didn't change elements to be removed by this request.

the new tab bar was removed from history and bookmarks, as currently they are pages just like the settings and downloads pages, using the new tab button from these pages is confusing ux. the new tab bar will only be displayed on the tab list. 

This also enables us to consider moving these pages to actual tabs, as the new tab page is. if we do that in the future, it will still make sense to not have the tab bar,

2021-01-29 15:33 UTC, UniversalSuperBox requested changes
Please try installing this change and checking for warnings when loading these pages.

2021-01-29 15:33 UTC, UniversalSuperBox commented on src/app/webbrowser/BookmarksView.qml
> -        id: toolbar
Removing the toolbar broke anchors to the toolbar in this file.

2021-01-29 15:33 UTC, UniversalSuperBox commented on src/app/webbrowser/BookmarksViewWide.qml
> -        id: toolbar
Removing the toolbar broke anchors to the toolbar in this file.

2021-01-29 15:33 UTC, UniversalSuperBox commented on src/app/webbrowser/HistoryView.qml
> -        id: toolbar
Removing the toolbar broke anchors to the toolbar in this file.

2021-01-29 15:33 UTC, UniversalSuperBox commented on src/app/webbrowser/HistoryViewWide.qml
> -        id: bottomToolbar
Removing the bottomToolbar broke anchors to the toolbar in this file.

2021-02-03 15:52 UTC, mateosalta commented
Ah, sorry @UniversalSuperBox I messed it up with the merge conflict

2021-02-04 18:44 UTC, mateosalta reviewed
anchors replaced to not link to toolbar

2021-05-14 18:53 UTC, UniversalSuperBox approved these changes
Changes look good, let's do it.

2021-05-14 18:54 UTC, merged

2021-05-17 16:28 UTC, mateosalta commented
nice :) getting more consistant. i do need to work more on the sub-domain page.

2021-05-18 05:24 UTC, mateosalta commented
ok, further tweaking of the strange sub page "ExpandedHistoryView" https://github.com/ubports/morph-browser/pull/488