Set Desktop Mode from Main Menu
ubports/morph-browser pull request #397
Opened 2020-10-11 10:24 UTC by niutech

This small addition shows the _Set Desktop Mode_ checkable action in the Main / Hamburger Menu, so that users can easily switch between the desktop and mobile versions of the web page. Fixes #324.

2020-10-17 13:04 UTC, balcy commented
If it's at the bottom of the menu I think it's fine to add it in my opinion. (It can be ignored by users who not need it)

2020-10-26 05:32 UTC, kugiigi commented
In my opinion, this actually deserves to be in the menu more than some of the current ones like "Save / Print to PDF".
If the menu is versatile, it would be ideal to rearrange the menu into maybe sub-menus and actual controls like for zoom 😄

2020-10-26 13:56 UTC, balcy approved these changes

2020-11-23 22:46 UTC, UniversalSuperBox requested changes
Hey, that's really neat! Thank you! This is a little strange to use, though...

This menu item does not change to reflect whether desktop mode is on or off. I think the icon and/or text should change to reflect what you're about to set (assuming you can't put an actual checkbox there). Check out our list of icons to see some possible candidates:

https://docs.ubports.com/projects/icons/en/latest/

I might suggest the text being "Set desktop mode" and "Set mobile mode" or something more clear, and the icons being `phone-smartphone-symbolic` and `computer-symbolic` for which you would set if you tapped the icon.

Might also be a good idea to only show the action if the device is small enough to actually switch between the two modes!

2020-11-23 23:37 UTC, niutech commented
@UniversalSuperBox I can make these changes, but why can't we use a generic [checkable action](https://doc.qt.io/qt-5/qml-qtquick-controls2-action.html#checkable-prop) with a checkbox like this:
![checkable action](http://zetcode.com/img/gui/qt5/checkable.png)

2020-11-24 14:16 UTC, UniversalSuperBox commented
If that works, yes, just do that :)

2023-10-07 23:12 UTC, closed without merging