Adds navigation history in the back/forward button
ubports/morph-browser pull request #444
Opened 2021-01-05 18:07 UTC by kugiigi

Press-and-hold and right-click on the back and forward buttons will open a popup with the navigation history just like on other browsers. Currently, it uses `Popover` with custom background color since it doesn't "popup" enough on white contents which websites usually are. I will try to use Popup/Menu from QQC2 and see if it looks better.

This is an expansion of the initial effort in #428 . @lduboeuf  and I already talked about this :smiley:

2021-01-07 17:20 UTC, kugiigi commented
This needs #430 otherwise, the popup is rotated.
#442 would also make the style look better.

2021-01-07 17:30 UTC, kugiigi commented
Here's some screenshots
![screenshot20210108_012533836](https://user-images.githubusercontent.com/29456786/103924489-0ef3ed80-5151-11eb-8201-10d9c2a57ac1.png)
![screenshot20210108_012600989](https://user-images.githubusercontent.com/29456786/103924494-10251a80-5151-11eb-9c8c-85b4736f9093.png)
![screenshot20210108_012658893](https://user-images.githubusercontent.com/29456786/103924496-10bdb100-5151-11eb-9d38-1dad995d4bfc.png)

2021-02-04 17:38 UTC, UniversalSuperBox requested changes
Erm... Well... I guess I have to say it again.

This PR has a merge conflict.

2021-05-25 19:15 UTC, UniversalSuperBox approved these changes

2021-05-25 19:16 UTC, merged