Translations update from Weblate
ubports/morph-browser pull request #482
Opened 2021-04-16 13:44 UTC by ubports-weblate

Translations update from [Weblate](https://translate.ubports.com/projects/ubports/morph-browser/) for UBports/Morph Browser.

2021-04-19 21:29 UTC, UniversalSuperBox requested changes
@Flohack74, this translation seems invalid. https://github.com/ubports/morph-browser/pull/482/files#diff-0a4a9ca503c41c5f2a54de36293d8863d6ef72d42476226fa0b9eddf52bc94e9R499

2021-05-13 15:49 UTC, dobey commented
> @Flohack74, this translation seems invalid. https://github.com/ubports/morph-browser/pull/482/files#diff-0a4a9ca503c41c5f2a54de36293d8863d6ef72d42476226fa0b9eddf52bc94e9R499

Can you just "fix" it on weblate and let it update this branch so that the broken translation isn't there?

2021-05-17 09:46 UTC, Flohack74 commented
Should be fixed now...

2021-05-17 14:25 UTC, dobey approved these changes

2021-05-18 14:32 UTC, UniversalSuperBox approved these changes

2021-05-18 14:32 UTC, merged